font:
  #normal:
  #  family: Hack Nerd Font
  #size: 12
  #offset:
  #  x: 0
  #  y: 0

  #normal:
  #  family: JetBrainsMono Nerd Font
  #size: 14
  #offset:
  #  x: 0
  #  y: 0

  #normal:
  #  family: GohuFont Nerd Font
  #size: 14
  #offset:
  #  x: 0
  #  y: 0

  #normal:
  #  family: Monoid Tight
  #size: 12
  #offset:
  #  x: 0
  #  y: 0

  normal:
    family: Mononoki Nerd Font
    style: Regular
  size: 12 #16
  offset:
    x: 1
    y: 0

# Colors (Solarized Dark)
colors:
  # Default colors
  primary:
    background: '0x002b36'
    foreground: '0x839496'

  # Normal colors
  normal:
    black:   '0x073642'
    red:     '0xdc322f'
    green:   '0x859900'
    yellow:  '0xb58900'
    blue:    '0x268bd2'
    magenta: '0xd33682'
    cyan:    '0x2aa198'
    white:   '0xeee8d5'

  # Bright colors
  bright:
    black:   '0x002b36'
    red:     '0xcb4b16'
    green:   '0x586e75'
    yellow:  '0x657b83'
    blue:    '0x839496'
    magenta: '0x6c71c4'
    cyan:    '0x93a1a1'
    white:   '0xfdf6e3'

selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  #semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true
